apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumber-server
spec:
  selector:
    matchLabels:
      app: dumber-server
  template:
    metadata:
      labels:
        app: dumber-server
    spec:
      containers:
      - name: dumber-server
        image: quay.io/gfarache/dumber-server:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health        
            port: 8080           
          initialDelaySeconds: 10
          periodSeconds: 15      
          failureThreshold: 3    
        readinessProbe:
          httpGet:
            path: /health        
            port: 8080           
          initialDelaySeconds: 5 
          periodSeconds: 10      
          failureThreshold: 3    
---
apiVersion: v1
kind: Service
metadata:
  name: dumber-server-service
spec:
  selector:
    app: dumber-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
