quarkus.swagger-ui.always-include=true
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.host=0.0.0.0
quarkus.http.enable-compression=true
quarkus.devservices.enabled=false

quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://host.docker.internal:7007}
# not a secret
quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${NOTIFICATIONS_BEARER_TOKEN:bXljdXJscGFzc3dkCg==}

mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
mp.messaging.incoming.kogito_incoming_stream.path=/


quarkus.openapi-generator.simple_server_yaml.auth.BearerToken.token-propagation=true
quarkus.openapi-generator.simple_server_yaml.auth.BearerToken.header-name=X-Authorization-First



quarkus.openapi-generator.simple_server_yaml.auth.BearerTokenOther.token-propagation=true
quarkus.openapi-generator.simple_server_yaml.auth.BearerTokenOther.header-name=X-Authorization-Other

quarkus.openapi-generator.simple_server_yaml.auth.SimpleBearerToken.token-propagation=true
quarkus.openapi-generator.simple_server_yaml.auth.SimpleBearerToken.header-name=X-Authorization-Simple

quarkus.rest-client.simple_server_yaml.url=http://simple-server-service.sonataflow-infra

quarkus.log.category."org.apache.http".level=DEBUG

kie.flyway.enabled = true
kogito.persistence.headers.enabled = true
quarkus.log.category."org.jbpm.flow.serialization.impl".level=DEBUG

